= Cinnamon 4

A new implementation of the Cinnamon 3 CMS server in Java.

Current status: pre-alpha.

== Goal

Implement the core features of the Cinnamon CMS in Java,

* using modern language features,
* with unit tests,
* with integration tests,
* with documentation,
* improved API,
* removing obsolete code,
* minimizing dependencies on huge frameworks which are hard to understand and difficult to update.

== Dependencies

Version numbers describe the minimum version. You can either download them directly and install them manually (recommended for Java) or use your system's package manager (Linux) or the Windows installer.

=== Run the binary version

To run the binary release (not available yet, you have to build from source), you just need

* https://adoptopenjdk.net/[Java 16]
* https://www.postgresql.org/download/[PostgreSQL 12]

=== Build & run from source

* https://adoptopenjdk.net/[Java 16]
* https://www.postgresql.org/download/[PostgreSQL 12]
* https://git-scm.com/downloads[Git] (optional for build, required for developers)
* https://maven.apache.org/download.cgi[Apache Maven 3.8.1] (as build system)

== Initial Setup

* link:docs/install_on_windows.adoc[Installation on Windows]
* link:docs/install_on_linux.adoc[Installation on Linux]

TODO: add a test database for initial production setup

== Build

In the top level project directory, run:

    mvn clean package

to build target/cinnamon-server.jar which includes all dependencies. This will also run a full integration
test and create a lot of basic objects in the cinnamon_test database. If this succeeds, the system is okay.

== Run

    java -jar target/cinnamon-server.jar

will start the server with default settings.

Run

    java -jar target/cinnamon-server.jar --help

to show the command line options.

    # write the default config to a file:
    java -jar target/cinnamon-server.jar --write-config my-config.xml

    # load a custom config file:
    java -jar target/cinnamon-server.jar --config my-config.xml

    # start on port 8080:
    java -jar target/cinnamon-server.jar --port 8080

== Configure

TODO: explain/document configuration settings https://github.com/dewarim/cinnamon4/issues/215[issue #125]

See the file default-config.xml[default-config.xml] for the default values.

== License

[Apache 2.0](LICENSE.txt)

  Copyright 2018 Ingo Wiarda

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

== Author

Ingo Wiarda - ingo_wiarda@dewarim.de