== Installation on Linux

=== Database

* Use your package manager to install the current version of PostgreSQL (12+).

    # Ubuntu example:
    sudo apt install postgresql

* Create a database "cinnamon_test", owned by user "cinnamon" with password "cinnamon"
either with pgAdmin or https://medium.com/coding-blocks/creating-user-database-and-adding-access-on-postgresql-8bfcd2f4a91e[directly with postgres].

    sudo -u postgres psql
    postgres=# create user cinnamon_test with encrypted password 'cinnamon';
    postgres=# alter user cinnamon with LOGIN;
    postgres=# create database cinnamon_test with owner cinnamon;

* Make sure PostgreSQL runs as a service on startup.

=== Java

You can either use your system's package manager to install a version of the OpenJDK or install an independent version locally. I recommend the latter, as then Cinnamon won't break if your system's version is too old, although you will have to install security updates manually. This document assumes you will use the manual installation.

* Download  https://adoptopenjdk.net/[Java 16] (or a newer version).
* Unpack the downloaded file.
* Add Java to your PATH (for example by adding it to the end of .bashrc in your home directory)

    export JAVA_HOME=/home/${USER}/bin/jdk-16
    export PATH=${JAVA_HOME}/bin:$PATH

You may have to restart / re-login to have this take effect.

=== Automatically start server on boot

see: https://www.baeldung.com/linux/run-java-application-as-service[run application as service]

you will need to start after Cinnamon after Postgresql, so (untested):

  [Unit]
  Description=Cinnamon Server Service
  After=syslog.target network.target postgresql.service

=== Development

* Install https://git-scm.com/downloads[Git]
* Install https://maven.apache.org/download.cgi[Apache Maven 3.8.1] (or newer)
* Add Maven to your PATH (for example by adding it to the end of .bashrc in your home directory)

    export MAVEN_HOME=/home/${USER}/bin/maven
    export PATH=${JAVA_HOME}/bin:${MAVEN_HOME}/bin:$PATH

* Logout & login again. (Or restart the system)
* Check if everything works:

    java -version
    git version
    mvn -version

* Check out the current version of Cinnamon:

    git clone git@github.com:dewarim/cinnamon4.git

