== Configuring Apache Tika for Cinnamon Server

Apache Tika can be used to index metadata of binary documents in Cinnamon, for example PDF and image metadata.

Your config file must include:

[source,xml]
----
  <cinnamonTikaConfig>
    <baseUrl>http://localhost:9998</baseUrl>
    <useTika>true</useTika>
  </cinnamonTikaConfig>
----

If you do not want to use tika, simply set useTika to false.
The default is "<useTika>false</useTika>".

=== Configure Formats

For each format in the formats database table, you can set the index_mode to "TIKA". Alternate options are XML, PLAIN_TEXT and NONE (content will not be indexed).

=== Tika Metaset

The metadata generated by Tika is stored in a tika metaset, so you must configure the corresponding metaset-type:

[source,sql]
----
insert into metaset_types(id, name, is_unique) VALUES (nextval('seq_metaset_type_id'), 'tika', true);
----

=== Installing Docker with Tika image

Note: you do not have to use docker - if you install the Tika server yourself with all dependencies, that's fine, too.

on Ubuntu:

* sudo apt install docker.io
* sudo docker pull apache/tika:latest-full
* sudo docker run -d -p 9998:9998 apache/tika:latest-full

This will run the official Tika image. To stop, use:

  # to find the Container ID:
  sudo docker ps
  # using the Container ID:
  sudo docker stop 8360599b464e

(TODO: how to set up as a background service)